twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
<<<<<<< HEAD
        strict_variables: true
=======
        strict_variables: true
>>>>>>> feryelPI
