<?php

namespace ContainerZUlOT2c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EKTaUydService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EKTaUyd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticator' => ['privates', 'App\\Security\\LoginFormAuthenticator', 'getLoginFormAuthenticatorService', true],
            'clientRegistry' => ['services', 'knpu.oauth2.registry', 'getKnpu_Oauth2_RegistryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
        ], [
            'authenticator' => 'App\\Security\\LoginFormAuthenticator',
            'clientRegistry' => '?',
            'em' => '?',
            'hasher' => '?',
            'userAuthenticator' => '?',
        ]);

        if (isset($container->privates['.service_locator.EKTaUyd'])) {
            return $container->privates['.service_locator.EKTaUyd'];
        }

        return $container->privates['.service_locator.EKTaUyd'] = $instance;
    }
}
