<?php

namespace ContainerHDeD5KF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QC3Bd3nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qC3Bd3n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qC3Bd3n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'resetService' => ['privates', 'App\\Service\\PasswordResetService', 'getPasswordResetServiceService', true],
        ], [
            'em' => '?',
            'resetService' => 'App\\Service\\PasswordResetService',
        ]);
    }
}
