<?php

namespace ContainerHDeD5KF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7p6ely2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7p6ely2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'resetService' => ['privates', 'App\\Service\\PasswordResetService', 'getPasswordResetServiceService', true],
        ], [
            'em' => '?',
            'hasher' => '?',
            'resetService' => 'App\\Service\\PasswordResetService',
        ]);

        if (isset($container->privates['.service_locator.7p6ely2'])) {
            return $container->privates['.service_locator.7p6ely2'];
        }

        return $container->privates['.service_locator.7p6ely2'] = $instance;
    }
}
