<?php

namespace ContainerHDeD5KF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordResetServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PasswordResetService' shared autowired service.
     *
     * @return \App\Service\PasswordResetService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PasswordResetService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }

        $instance = new \App\Service\PasswordResetService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), new \Symfony\Component\Mailer\Mailer($a, NULL, $b), $container->getEnv('MAILER_FROM'));

        if (isset($container->privates['App\\Service\\PasswordResetService'])) {
            return $container->privates['App\\Service\\PasswordResetService'];
        }

        return $container->privates['App\\Service\\PasswordResetService'] = $instance;
    }
}
