<?php

namespace ContainerDi96NJN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A7uNT0fService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a7uNT0f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'mailer' => '?',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);

        if (isset($container->privates['.service_locator.a7uNT0f'])) {
            return $container->privates['.service_locator.a7uNT0f'];
        }

        return $container->privates['.service_locator.a7uNT0f'] = $instance;
    }
}
