<?php

namespace ContainerDi96NJN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HXS1QqPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HXS1QqP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ForgotPasswordController::request' => ['privates', '.service_locator.a7uNT0f', 'get_ServiceLocator_A7uNT0fService', true],
            'App\\Controller\\ForgotPasswordController::reset' => ['privates', '.service_locator.AJWI_5m', 'get_ServiceLocator_AJWI5mService', true],
            'App\\Controller\\GoogleAuthController::connectAction' => ['privates', '.service_locator.hokdgZZ', 'get_ServiceLocator_HokdgZZService', true],
            'App\\Controller\\GoogleAuthController::connectCheckAction' => ['privates', '.service_locator.EKTaUyd', 'get_ServiceLocator_EKTaUydService', true],
            'App\\Controller\\ProfileController::changePassword' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\ProfileController::updateInfo' => ['privates', '.service_locator.YAelVMf', 'get_ServiceLocator_YAelVMfService', true],
            'App\\Controller\\ProfileController::updatePhoto' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UsersController::ban' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController::create' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\UsersController::delete' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController::demote' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController::edit' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController::index' => ['privates', '.service_locator.7V7yRiC', 'get_ServiceLocator_7V7yRiCService', true],
            'App\\Controller\\UsersController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UsersController::promote' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController::show' => ['privates', '.service_locator.A0o8nYx', 'get_ServiceLocator_A0o8nYxService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ForgotPasswordController:request' => ['privates', '.service_locator.a7uNT0f', 'get_ServiceLocator_A7uNT0fService', true],
            'App\\Controller\\ForgotPasswordController:reset' => ['privates', '.service_locator.AJWI_5m', 'get_ServiceLocator_AJWI5mService', true],
            'App\\Controller\\GoogleAuthController:connectAction' => ['privates', '.service_locator.hokdgZZ', 'get_ServiceLocator_HokdgZZService', true],
            'App\\Controller\\GoogleAuthController:connectCheckAction' => ['privates', '.service_locator.EKTaUyd', 'get_ServiceLocator_EKTaUydService', true],
            'App\\Controller\\ProfileController:changePassword' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\ProfileController:updateInfo' => ['privates', '.service_locator.YAelVMf', 'get_ServiceLocator_YAelVMfService', true],
            'App\\Controller\\ProfileController:updatePhoto' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.qrNhk2c', 'get_ServiceLocator_QrNhk2cService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UsersController:ban' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController:create' => ['privates', '.service_locator.9A_qgEI', 'get_ServiceLocator_9AQgEIService', true],
            'App\\Controller\\UsersController:delete' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController:demote' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController:edit' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController:index' => ['privates', '.service_locator.7V7yRiC', 'get_ServiceLocator_7V7yRiCService', true],
            'App\\Controller\\UsersController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\UsersController:promote' => ['privates', '.service_locator.KpciZEb', 'get_ServiceLocator_KpciZEbService', true],
            'App\\Controller\\UsersController:show' => ['privates', '.service_locator.A0o8nYx', 'get_ServiceLocator_A0o8nYxService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ForgotPasswordController::request' => '?',
            'App\\Controller\\ForgotPasswordController::reset' => '?',
            'App\\Controller\\GoogleAuthController::connectAction' => '?',
            'App\\Controller\\GoogleAuthController::connectCheckAction' => '?',
            'App\\Controller\\ProfileController::changePassword' => '?',
            'App\\Controller\\ProfileController::updateInfo' => '?',
            'App\\Controller\\ProfileController::updatePhoto' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UsersController::ban' => '?',
            'App\\Controller\\UsersController::create' => '?',
            'App\\Controller\\UsersController::delete' => '?',
            'App\\Controller\\UsersController::demote' => '?',
            'App\\Controller\\UsersController::edit' => '?',
            'App\\Controller\\UsersController::index' => '?',
            'App\\Controller\\UsersController::new' => '?',
            'App\\Controller\\UsersController::promote' => '?',
            'App\\Controller\\UsersController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ForgotPasswordController:request' => '?',
            'App\\Controller\\ForgotPasswordController:reset' => '?',
            'App\\Controller\\GoogleAuthController:connectAction' => '?',
            'App\\Controller\\GoogleAuthController:connectCheckAction' => '?',
            'App\\Controller\\ProfileController:changePassword' => '?',
            'App\\Controller\\ProfileController:updateInfo' => '?',
            'App\\Controller\\ProfileController:updatePhoto' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UsersController:ban' => '?',
            'App\\Controller\\UsersController:create' => '?',
            'App\\Controller\\UsersController:delete' => '?',
            'App\\Controller\\UsersController:demote' => '?',
            'App\\Controller\\UsersController:edit' => '?',
            'App\\Controller\\UsersController:index' => '?',
            'App\\Controller\\UsersController:new' => '?',
            'App\\Controller\\UsersController:promote' => '?',
            'App\\Controller\\UsersController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.HXS1QqP'])) {
            return $container->privates['.service_locator.HXS1QqP'];
        }

        return $container->privates['.service_locator.HXS1QqP'] = $instance;
    }
}
