<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVrcSYUF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVrcSYUF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVrcSYUF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVrcSYUF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVrcSYUF\App_KernelDevDebugContainer([
    'container.build_hash' => 'VrcSYUF',
    'container.build_id' => '4226e36a',
    'container.build_time' => 1775738352,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVrcSYUF');
